@startuml MobileApp

class MainFollowHeathyScreen {

}

class Schedule {
    + id: String
    + doctorId: String
    + roomId: String
    + day: String
    + session: String
}

class HeartBeat{ 
    + id : String
    + patientId : String
    + createdAt : Date
    + systole: float
    + diastole : float
    + heatBeat: float
}

class BMI{
    + id : String
    + patientId : String
    + createdAt : Date
    + tall: float
    + weigh : float
    + bmi: float
}



class Account{
    + id : String
    + username: String
    + password: String
    + role : Role
}
class Patient{
    + id : String
    + avatar : String
    + fullName : String
    + birthDate : Date
    + gender : Gender
    + address : String
}
class Department{
    + id : String
    + name : String
}
class Doctor{
    + id : String
    + avatar : String
    + fullName : String
    + birthDate : Date
    + gender : Gender
    + department : String
}
class Room{
    + id : String
    + name : String
    + department : String
}
class Position{
    + id : String
    + number : int
    + patientId : String
    + roomId : String
    + state : PositionState
}
class Record{
    + id : String
    + patientId : String
    + doctorId : String
    + name : String
    + precription : String
    + fileStore: String
}

Patient "1" - "1" Account
Account "1" - "1" Doctor
Doctor "many" -- "1" Department
Room "many" -- "1" Department
Patient "1" - "many" Position
Room "1" - "many" Position
Record "many" - "1" Patient
Record "many" - "1" Doctor

BMI "many" - "1" Patient
HeartBeat "many" - "1" Patient
Schedule "many" - "many" Doctor
Schedule "many" - "many" Room
@enduml
