@startuml Signup
actor Patient 
boundary ProfileDoctor 
control ScheduleController
control RoomController
boundary DoctorCheduleScreen
control PositionController
entity Position 


activate Patient
Patient -> ProfileDoctor: Nhấn chọn đặt lịch

activate ProfileDoctor
ProfileDoctor -> ScheduleController: Lấy danh sách ngày làm việc của bác sĩ (doctorId)
ProfileDoctor -> RoomController: Lấy danh sách phòng theo bác sĩ
ProfileDoctor -> ProfileDoctor: Open calandar
ProfileDoctor -> DoctorCheduleScreen: Send list schedule, list room, date, doctor
activate DoctorCheduleScreen
DoctorCheduleScreen -> DoctorCheduleScreen: lấy tên room theo ID, thời gian session
Patient -> DoctorCheduleScreen: chọn buổi khám
DoctorCheduleScreen -> PositionController: Tạo number, kiểm tra xem đã tồn tại chưa
PositionController -> Position:Tạo position
DoctorCheduleScreen -> Patient: thông báo kết quả đăng kí
@enduml