@startgantt My Doctor
saturday are closed
sunday are closed
Project starts 2021-08-02
-- Phase 1 --
[Research and install technology] on {An, Yen} lasts 5 days
[Description function] on {An, Yen} lasts 1 days
[Design data] on {An, Yen} starts at [Description function]'s end and lasts 2 days
[Design diagram] on {An, Yen} starts at [Description function]'s end and lasts 3 days
[Design mockup] on {An, Yen} starts at [Description function]'s end and lasts 4 days
[Code and deploy API] on {An, Yen} starts at [Design data]'s end and lasts 7 days
[Completed phase 1] happens 2021-08-13

-- Phase 2 --
[Testing phase 1] on {An, Yen} starts at [Completed phase 1]'s end and lasts 1 days
[Research used object on phase 2] on {An, Yen} starts at [Completed phase 1]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 1st] on {An, Yen} starts at [Completed phase 1]'s end and lasts 10 days

[Signin mobile] on {Yen} starts at [Completed phase 1]'s end and lasts 3 days
[Home mobile] on {Yen} starts at [Signin mobile]'s end and lasts 4 days
[Logout mobile] on {Yen} starts at [Home mobile]'s end and lasts 3 days

[Signup] on {An} starts at [Completed phase 1]'s end and lasts 5 days
[ForgotPass] on {An} starts at [Completed phase 1]'s end and lasts 5 days
[AuthOTP] on {An} starts at 2021-08-23 and lasts 5 days
[Completed phase 2] happens 2021-08-27

-- Phase 3 --
[Testing phase 2] on {An, Yen} starts at [Completed phase 2]'s end and lasts 1 days
[Research used object on phase 3] on {An, Yen} starts at [Completed phase 2]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 2nd] on {An, Yen} starts at [Completed phase 2]'s end and lasts 10 days

[FollowHealthy] on {Yen} starts at [Completed phase 2]'s end and lasts 10 days

[Profile] on {An} starts at [Completed phase 2]'s end and lasts 5 days
[ChangePass] on {An} lasts 5 days and starts at [Profile]'s end
[Completed phase 3] happens 2021-09-10

-- Phase 4 --
[Testing phase 3] on {An, Yen} starts at [Completed phase 3]'s end and lasts 1 days
[Research used object on phase 4] on {An, Yen} starts at [Completed phase 3]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 3rd] on {An, Yen} starts at [Completed phase 3]'s end and lasts 10 days

[Contact Doctor] on {Yen} starts at [Completed phase 3]'s end and lasts 10 days

[DoctorList] on {An} starts at [Completed phase 3]'s end and lasts 5 days
[DepartmentList] on {An} starts at [DoctorList]'s end and lasts 5 days
[Completed phase 4] happens 2021-09-24

-- Phase 5 --
[Testing phase 4] on {An, Yen} starts at [Completed phase 4]'s end and lasts 1 days
[Research used object on phase 5] on {An, Yen} starts at [Completed phase 4]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 4th] on {An, Yen} starts at [Completed phase 4]'s end and lasts 10 days

[Booking by Doctor] on {Yen} starts at [Completed phase 4]'s end and lasts 10 days

[Booking by Department] on {An} starts at [Completed phase 4]'s end and lasts 10 days and is 0% completed
[Completed phase 5] happens 2021-10-8

-- Phase 6 --
[Testing phase 5] on {An, Yen} starts at [Completed phase 5]'s end and lasts 1 days
[Research used object on phase 6] on {An, Yen} starts at [Completed phase 5]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 5th] on {An, Yen} starts at [Completed phase 5]'s end and lasts 10 days

[Payment] on {Yen} starts at [Completed phase 5]'s end and lasts 10 days

[FollowPosition] on {An} starts at [Completed phase 5]'s end and lasts 5 days
[FollowRecord] on {An} starts at [FollowPosition]'s end and lasts 5 days
[Completed phase 6] happens 2021-10-22

-- Phase 7 --
[Testing phase 6] on {An, Yen} starts at [Completed phase 6]'s end and lasts 1 days
[Research used object on phase 7] on {An, Yen} starts at [Completed phase 6]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 6th] on {An, Yen} starts at [Completed phase 6]'s end and lasts 10 days

[Signin web] on {An} starts at [Completed phase 6]'s end and lasts 3 days
[ManageRecord] on {An} starts at [Signin web]'s end and lasts 7 days

[Home web] on {Yen} starts at [Completed phase 6]'s end and lasts 7 days
[Logout web] on {Yen} starts at [Home web]'s end and lasts 3 days
[Completed phase 7] happens 2021-11-5

-- Phase 8 --
[Testing phase 7] on {An, Yen} starts at [Completed phase 7]'s end and lasts 1 days
[Research used object on phase 8] on {An, Yen} starts at [Completed phase 7]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 7th] on {An, Yen} starts at [Completed phase 7]'s end and lasts 10 days

[AnswerPatient] on {Yen} starts at [Completed phase 7]'s end and lasts 10 days

[UsedPosition] on {An} starts at [Completed phase 7]'s end and lasts 3 days
[CreateTestPosition] on {An} starts at [UsedPosition]'s end and lasts 7 days
[Completed phase 8] happens 2021-11-19

-- Phase 9 --
[Testing phase 8] on {An, Yen} starts at [Completed phase 8]'s end and lasts 1 days
[Research used object on phase 9] on {An, Yen} starts at [Completed phase 8]'s end and lasts 5 days
[Update request, data, diagram, mockup and API 8th] on {An, Yen} starts at [Completed phase 8]'s end and lasts 10 days

[Completed phase 9] happens 2021-12-3

-- Phase 10 --
[Testing phase 9 and deploy] on {An, Yen} starts at [Completed phase 9]'s end and lasts 5 days
[Completed document and demo] on {An, Yen} starts at [Testing phase 9 and deploy]'s end and lasts 5 days
[Completed phase 10] happens 2021-12-17
@endgantt
